/**
 * Design token type definitions
 * These mirror the structure of tokens generated by Style Dictionary
 */

export interface ColorTokens {
  background: {
    primary: string;
    secondary: string;
    tertiary: string;
  };
  surface: {
    primary: string;
    secondary: string;
    tertiary: string;
  };
  text: {
    primary: string;
    secondary: string;
    tertiary: string;
    inverse: string;
  };
  border: {
    primary: string;
    secondary: string;
    focus: string;
  };
  accent: {
    primary: string;
    secondary: string;
    hover: string;
    active: string;
  };
  error: {
    primary: string;
    background: string;
  };
  success: {
    primary: string;
    background: string;
  };
}

export interface SpacingTokens {
  xs: string;
  sm: string;
  md: string;
  lg: string;
  xl: string;
  '2xl': string;
  '3xl': string;
}

export interface TypographyTokens {
  fontFamily: {
    body: string;
    heading: string;
    code: string;
  };
  fontSize: {
    body: string;
    small: string;
    large: string;
    heading1: string;
    heading2: string;
    heading3: string;
  };
  fontWeight: {
    body: string;
    heading: string;
    button: string;
  };
  lineHeight: {
    body: number;
    heading: number;
  };
}

export interface BorderRadiusTokens {
  button: string;
  input: string;
  checkbox: string;
  card: string;
}

export interface ShadowTokens {
  button: string;
  card: string;
  modal: string;
  focus: string;
}

/**
 * Complete theme structure
 */
export interface Theme {
  color: ColorTokens;
  spacing: SpacingTokens;
  typography: TypographyTokens;
  borderRadius: BorderRadiusTokens;
  shadow: ShadowTokens;
}

